### ISSUE TITLE
Counter too large on first build

### ISSUE THREAD

**Issue by jneem** [jirilebl/diffyqs#1]
When cloning and building for the first time, latex died with a "Counter too large" error: it was running out of footnote numbers. Apparently this is a [known issue](https://tex.stackexchange.com/questions/342617/multiple-footnotes-using-symbols-produces-error-counter-too-large/342621) when using footnote symbols, because on the first run the page breaks aren't yet known.

My solution was to edit diffyqssetup.sty to change to numeric footnotes, then compile, then switch back to footnote symbols. I don't know if there's a nicer "permanent" solution, but it might be worth documenting.

**Comment by jirilebl** [comment]
I made the counter error into a warning.  That way on first pass it just warns but doesn't actually stop the compile.
